name: "Deploy, Test, Deploy stock portfolio application"

on: 
    workflow_dispatch:
    push:

permissions:
    id-token: write # required for the az login
    contents: read # required for checkout

jobs:
    stock_portfolio_app_build_and_test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Stock Portfolio Repo
            uses: actions/checkout@v4

          - name: Setup Python
            id: setup_python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
                cache: pip

          - name: Install Dependencies
            run: |
                python -m venv stockportfoliovenv
                source stockportfoliovenv/bin/activate
                pip install -r requirements.txt

          - name: Run Unit and Functional Tests
            run: |
                source stockportfoliovenv/bin/activate
                python -m pytest tests/unit
                python -m pytest tests/functional

    stock_portfolio_app_deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Stock Portfolio Repo
            uses: actions/checkout@v4

          - name: Azure login
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          - name: Install dependencies
            run: |
                python -m venv stockportfoliovenv
                source stockportfoliovenv/bin/activate
                pip install -r requirements.txt

          - name: Prepare Deployment Package
            run: |
                zip -r --quiet Application.zip .

          - name: Deploy app
            uses: azure/webapps-deploy@v3
            with:
              app-name: stocks-portfolio
              package: ${{ github.workspace }}/Application.zip







